name: Completed Feature Workflow

on:
  pull_request:
    branches: [ develop ]
    types: [closed]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update-merged-issue-issues:
    if: github.event.pull_request.merged_by != '' && github.actor != 'dependabot[bot]' && startsWith(github.head_ref, 'feature/issue-')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Extract Issue Number
        shell: bash
        env:
          HEAD_REF: ${{ github.head_ref }}
        run: echo "issue=$(echo "$HEAD_REF" | sed 's|[^0-9]||g')" >> $GITHUB_OUTPUT
        id: extract_issue
      - name: Output Issue Number
        env:
          ISSUE_NUMBER: ${{ steps.extract_issue.outputs.issue }}
        run: echo "Issue Number- $ISSUE_NUMBER"
      - name: Update Labels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ steps.extract_issue.outputs.issue }}
        run: gh issue edit $ISSUE_NUMBER --add-label "status:next release" --remove-label "status:in progress"
