name: In Progress Feature Workflow

on:
  push:
    branches:
    - feature/issue-*

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update-in-progress-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - name: Extract Issue Number
        shell: bash
        run: echo "issue=$(echo ${GITHUB_REF#refs/heads/} | sed 's|[^0-9]||g')" >> $GITHUB_OUTPUT
        id: extract_issue
      - name: Output Issue Number
        env:
          ISSUE_NUMBER: ${{ steps.extract_issue.outputs.issue }}
        run: echo "Issue Number- $ISSUE_NUMBER"
      - name: Update Labels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ steps.extract_issue.outputs.issue }}
        run: gh issue edit $ISSUE_NUMBER --add-label "in progress" --remove-label "to do"