name: Configure GitHub Issue Labels

on:
  push:
    paths:
      - ".github/workflows/label-configurer.yml"
      - ".github/labels.yml"

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@24d110aa46a59976b8a7f35518cb7f14f434c916
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          exclude: |
            *min review